version: "2.2"

services:
  dsp_node-server:
    container_name: dsp_node-server
    build:
      context: ./node-server
      dockerfile: node-server.dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGO_HOST=dsp_mongodb
      - MONGO_PORT=27017
    networks:
      - dsp_server_network

  dsp_mongodb:
    container_name: dsp_mongodb
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    environment:
      - HOST=dsp_node-server
      - PORT=5001
    networks:
      - dsp_server_network

  dsp_python-server:
    container_name: dsp_python-server
    build:
      context: ./server
      dockerfile: python-server.dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_SERVER_HOST=dsp_node-server
      - NODE_SERVER_PORT=5001
      - PYTHON_SERVER_HOST=0.0.0.0
      - PYTHON_SERVER_PORT=3000
    networks:
      - dsp_server_network

networks:
  dsp_server_network:
    name: dsp_server_network
